- src: https://github.com/redhat-cop/casl-ansible
  scm: git
  version: v3.7.2
  name: casl-ansible

- src: https://github.com/sherl0cks/openshift-apicurio
  scm: git
  version: master
  name: openshift-apicurio

